version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: OfnsQy3xg0GN03t5I3A+PA==
        databases:
          default:
            connector: postgres
            host: ec2-18-214-119-135.compute-1.amazonaws.com
            database: da7k5ruqqucqec
            user: ezpwblebdbyqyv
            password: ab694b8165d916e25865f9e8c81edfd9ef97f648252377357bdff6060f6d38bf
            ssl: true
            port: 5432
            migrations: true
